### PR TITLE
FIX: missing argument

### LINKED ISSUE #493: Error missing arguments while creating a plans.
Hi there,

I was got error while creating a plan.

```
PHP Fatal error:  Uncaught ArgumentCountError: 6 arguments are required, 5 given in /var/www/daloradius/app/operators/bill-plans-new.php:142
```

### PR DESCRIPTION
**Pull request by drosanda**
This will fix #493 

just add empty argument to end of method sprintf.

please let me know if any concern.

### CODE REVIEW

File: app/operators/bill-plans-new.php [hunk 1]
```diff
@@ -139,7 +139,7 @@
                         $format = "A new %s named %s has been successfully added to database. %d %s have been associated to this %s";
                         $successMsg = sprintf($format . ' [<a href="bill-plans-edit.php?planName=%s" title="Edit">Edit</a>]', t('all','PlanName'),
                                               $planName_enc, $groupsCount, t('title','Profiles'), t('all','PlanName'), urlencode($planName_enc));
-                        $logAction .= sprintf("$format on page: ", t('all','PlanName'), $groupsCount, t('title','Profiles'), t('all','PlanName'));
+                        $logAction .= sprintf("$format on page: ", t('all','PlanName'), $groupsCount, t('title','Profiles'), t('all','PlanName'), '');
```
Comment (lirantal) [inline app/operators/bill-plans-new.php:142]: Actually, it's rightfully missing an element because it expects 5 to complete the variables in the `$format` string. 

We can fix it like this:

```suggestion
                        $logAction .= sprintf("$format on page: ", t('all','PlanName'), $planName, $groupsCount, t('title','Profiles'), t('all','PlanName'));
```

**Review by lirantal — COMMENTED** [review]
Thanks for bringing up. I correct the log function call.
